image: anapsix/alpine-java:8_jdk

before_script:
  - which java
  - which javac

stages:
  - build
  - deploy
  - manual_deploy

build:
  stage: build
  before_script:
    - ./gradlew setupCiWorkspace
    - ./gradlew ciWriteBuildNumber
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 month

production:
  stage: deploy
  script: ./gradlew curseforge postDiscordNotification
  retry: 2
  when: on_success
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    refs:
      - tags

manual_production:
  stage: manual_deploy
  script: ./gradlew curseforge postDiscordNotification
  retry: 2
  when: manual
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    refs:
      - master
  except:
    refs:
      - tags
